18-Sep-2422:27:30-INFO-C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\devoir_python\mediatheque\librarian\views.py changed, reloading.
18-Sep-2422:35:34-INFO-C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\devoir_python\mediatheque\mediatheque\settings.py changed, reloading.
18-Sep-2422:39:52-INFO-C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\devoir_python\mediatheque\librarian\views.py changed, reloading.
18-Sep-2422:53:17-ERROR-Internal Server Error: /librarian/create_borrower
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\edit.py", line 134, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\http\response.py", line 618, in __init__
    self["Location"] = iri_to_uri(redirect_to)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\utils\encoding.py", line 134, in iri_to_uri
    iri = str(iri)
          ^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\utils\functional.py", line 119, in __str__
    return str(self.__cast())
               ^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\utils\functional.py", line 110, in __cast
    return func(*self._args, **self._kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail_borrower' with keyword arguments '{'pk': 'Laurent Gina'}' not found. 1 pattern(s) tried: ['librarian/borrower/(?P<pk>[0-9]+)/\\Z']
18-Sep-2422:57:31-INFO-C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\devoir_python\mediatheque\librarian\views.py changed, reloading.
18-Sep-2422:58:01-INFO-C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\devoir_python\mediatheque\librarian\views.py changed, reloading.
18-Sep-2422:58:28-ERROR-Internal Server Error: /librarian/create_borrower
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\edit.py", line 134, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\devoir_python\mediatheque\librarian\views.py", line 114, in get_success_url
    return render("detail_borrower", kwargs={"pk": self.object.name})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: render() got an unexpected keyword argument 'kwargs'
18-Sep-2422:59:02-INFO-C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\devoir_python\mediatheque\librarian\views.py changed, reloading.
18-Sep-2422:59:19-ERROR-Internal Server Error: /librarian/create_borrower
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\edit.py", line 134, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\devoir_python\mediatheque\librarian\views.py", line 114, in get_success_url
    return redirect("detail_borrower", kwargs={"pk": self.object.name})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail_borrower' with keyword arguments '{'kwargs': {'pk': 'Harry Potter'}}' not found. 1 pattern(s) tried: ['librarian/borrower/(?P<pk>[0-9]+)/\\Z']
18-Sep-2423:00:08-INFO-C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\devoir_python\mediatheque\librarian\urls.py changed, reloading.
18-Sep-2423:00:22-ERROR-Internal Server Error: /librarian/create_borrower
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\edit.py", line 134, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\devoir_python\mediatheque\librarian\views.py", line 114, in get_success_url
    return redirect("detail_borrower", kwargs={"pk": self.object.name})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail_borrower' with keyword arguments '{'kwargs': {'pk': 'Hermione Granger'}}' not found. 1 pattern(s) tried: ['librarian/borrower/(?P<pk>[^/]+)/\\Z']
18-Sep-2423:00:42-INFO-C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\devoir_python\mediatheque\librarian\urls.py changed, reloading.
18-Sep-2423:01:06-INFO-C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\devoir_python\mediatheque\librarian\views.py changed, reloading.
18-Sep-2423:01:22-ERROR-Internal Server Error: /librarian/create_borrower
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\edit.py", line 134, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\devoir_python\mediatheque\librarian\views.py", line 114, in get_success_url
    return redirect("detail_borrower", kwargs={"pk": self.object.id})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'detail_borrower' with keyword arguments '{'kwargs': {'pk': 9}}' not found. 1 pattern(s) tried: ['librarian/borrower/(?P<pk>[0-9]+)/\\Z']
18-Sep-2423:02:51-INFO-C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\devoir_python\mediatheque\librarian\views.py changed, reloading.
18-Sep-2423:03:19-ERROR-Internal Server Error: /librarian/create_borrower
Traceback (most recent call last):
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\edit.py", line 134, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\http\response.py", line 618, in __init__
    self["Location"] = iri_to_uri(redirect_to)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\mediatheque\Lib\site-packages\django\utils\encoding.py", line 135, in iri_to_uri
    return quote(iri, safe="/#%[]=:;$&()+,!?*@'~")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\urllib\parse.py", line 907, in quote
    return quote_from_bytes(string, safe)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\urllib\parse.py", line 937, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes
18-Sep-2423:08:39-INFO-C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\devoir_python\mediatheque\librarian\views.py changed, reloading.
18-Sep-2423:09:46-INFO-C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\devoir_python\mediatheque\librarian\views.py changed, reloading.
18-Sep-2423:11:26-INFO-C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\devoir_python\mediatheque\librarian\views.py changed, reloading.
18-Sep-2423:16:11-INFO-C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\devoir_python\mediatheque\librarian\views.py changed, reloading.
18-Sep-2423:23:36-INFO-C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\devoir_python\mediatheque\librarian\models.py changed, reloading.
18-Sep-2423:25:45-INFO-C:\Users\ameli\OneDrive\Documents\CEF\Devoirs\Partie_Wizard\POO\devoir_python\mediatheque\borrower\models.py changed, reloading.
